services:
  java:
    container_name: spring-application
    environment:
      - TZ=Asia/Tokyo
    build:
      context: ./docker/java
      dockerfile: Dockerfile
    volumes:
      - ../workspace:/workspace:cached # cached, delegated, default
    ports:
      - "8080:8080"
    command: sleep infinity
    depends_on:
      - mysql

  mysql:
    container_name: backend-mysql
    build:
      context: ./docker/database
      dockerfile: Dockerfile.mysql
    env_file:
      - ./docker/database/.env
    ports:
      - 3306:3306
    volumes:
      - ./docker/database/data:/var/lib/mysql
volumes:
  spring-store:
  spring-logs:
