services:
  java-for-spring:
    container_name: spring-application
    build:
      context: ./docker/java
      dockerfile: Dockerfile
    volumes:
      - ..:/work:cached # cached, delegated, default
    command: sleep infinity
